export const GET_MOVIES = 'GET_MOVIES'
export const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS'
export const GET_MOVIES_FAILED = 'GET_MOVIES_FAILED'
export const SET_SEARCH_INPUT_VALUE = 'SET_SEARCH_INPUT_VALUE'

export const GET_MOVIE_DETAILS = 'GET_MOVIE_DETAILS'
export const GET_MOVIE_DETAILS_SUCCESS = 'GET_MOVIE_DETAILS_SUCCESS'
export const GET_MOVIE_DETAILS_FAILED = 'GET_MOVIE_DETAILS_FAILED'



